#+title: ORG Feeds
#+author: Victor Dorneanu
#+startup: indent
#+hugo_base_dir: ../
#+hugo_auto_set_lastmod: t
#+property: header-args :eval never-export

#+macro: zk [[https://brainfck.org/#$1][$2]]
#+macro: bib [[https://brainfck.org/bib.html#$1][$2]]

* Feeds
:PROPERTIES:
:EXPORT_HUGO_SECTION: feeds
:EXPORT_HUGO_WEIGHT: auto
:END:
** Index
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :skip true :layout feeds :outputs rss
:EXPORT_FILE_NAME: _index
:END:
** First post                                                                  :linkedin:twitter:
:PROPERTIES:
:EXPORT_FILE_NAME: 2021-first-post
:END:
askjhsadkjhaskdhasd
asdkjahskdjhasd
asdkjhaskdhasd
#+hugo: more
- some content here
- bla
- alles klar
** 2nd post                                                                    :linkedin:golang:
:PROPERTIES:
:EXPORT_FILE_NAME: 2021-2nd-post
:END:
post summary.
#+hugo: more
My post content.
** Only twitter                                                                :twitter:
:PROPERTIES:
:EXPORT_FILE_NAME: 2021-only-twitter
:END:
post summary.
#+hugo: more
My post content.
** Simple post                                                                 :twitter:linkedin:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :posturl https://heise.de
:EXPORT_FILE_NAME: 2021-simple-post
:END:
Some text here and there.
- text here
- text [[https://google.de][some link]]
** The frustration with the productivity culture                               :linkedin:twitter:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :posturl https://www.newyorker.com/culture/office-space/the-frustration-with-productivity-culture/amp
:EXPORT_FILE_NAME: 2021-the-frustration-with-productivity-culture
:END:
 Next time you don't feel productive, keep in mind: "The software industry didn’t increase productivity by demanding more from its engineers; instead, it developed a more productive system to organize their efforts." Great reading on productivity (also applied to software engineering)!
** The unlikely story of Bitcoin and El Salvador                               :linkedin:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :posturl https://bitcoinmagazine.com/.amp/culture/the-polarity-of-bitcoin-in-el-salvador
:EXPORT_FILE_NAME: 2021-the-unlikely-story-of-bitcoin-and-el-salvador
:END:
I guess revolution is not happening in Western countries. Read this article if you want to know why El Salvador has adopted Bitcoin as an official currency.
A Salvadoran friend told me almost all of the historical background given in the article is true.

* Other feeds
:PROPERTIES:
:EXPORT_HUGO_SECTION: others
:EXPORT_HUGO_WEIGHT: auto
:END:
** Some post                                                                   :linkedin:
:PROPERTIES:
:EXPORT_FILE_NAME: 2021-some-post
:END:
- bla
- askjh

* COMMENT Local Variables                                                       :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
